services:
  app:
    container_name: zero_deeplearning
    build: 
      context: ./.docker
      dockerfile: Dockerfile
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
    volumes:
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/workspace